<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/admin.css">
    <title>Quiz</title>
</head>
<body>

    <header>
        <div>
            <img src="img/quiz_logo.png" alt="quiz logo" id="logo_header">
            <h1 class="logo_title">Créez vos propres quiz!</h1>
        </div>
        <nav class="nav-header">
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="?page=home"><i class="fas fa-home"></i> Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="?page=selectCategory"><i class="fas fa-question"></i> Choisissez votre quiz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="?page=admin"><i class="fas fa-user-cog"></i> Administration</a>
                </li>
            </ul>
        </nav>
    </header>

    <main class="container">
        <?php include 'views/' . $template . 'View.phtml' ?>
    </main>

    <footer>
    
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <script src="js/main.js"></script>
</body>
</html>