<section class="home">
    <h2>PAGE D'ACCUEIL</h2>
    <p><em>Bienvenue sur ce jeux de quiz qui vous permettra de tester vos connaissances sur divers catégories! Et créez les vôtres, afin d'en faire profitez vos amis ou votre famille!<br>
    Ne soyez pas juste simple joueur! Devenez le créateur du jeu!</em></p>
    <ol>
        <li>
            <h3>Démarrer une partie</h3>
            <p>Il vous suffit de cliquer sur l'onglet "Choisissez votre quiz", de sélectionner la catégorie qui vous intéresse et c'est parti ! C'est aussi simple que ça.</p>
            <p>A chaque question, vous disposez de 30 secondes pour choisir entre les 3 réponses proposées.</p>
            <p>Il y a 10 questions aléatoires par partie.</p>
        </li>
        <li>
            <h3>Créer vos propres questions et catégories</h3>
            <p>Vous pouvez ajouter autant de questions que vous le voulez sur toutes les catégories existantes et même créer vos propres thèmes!</p>
            <p>Pour cela, cliquez sur l'onglet "Administration".</p>
            <p>Vous avez ensuite le choix entre "ajouter une question", "supprimer une question ou un thème" et "modifier une question" :</p>
            <ul>
                <li>
                    <h4>Ajouter une question</h4>
                    <p>Pour ajouter une question, selectionnez tout d'abord le thème auquel appartient votre question, si vous préférez en créer un, cliquez à l'endroit indiqué, juste au dessus de la selection des catégories. Attention à l'orthographe ! Une fois la nouvelle catégorie créée, vous ne pourrez plus la modifier !</p>
                    <p>Posez ensuite votre question dans le champ de saisi prévu à cet effet.</p>
                    <p>Faites de même pour les 3 choix de réponse dans les 3 champs juste dessous (une seule réponse doit être correcte !).</p>
                    <p>Il ne vous reste plus qu'à indiquer laquelle des 3 réponses est la bonne et de cliquer sur "soumettre votre question" et le tour est joué !</p>
                </li>
                <li>
                    <h4>Supprimer une question ou un thème</h4>
                    <p>Pour supprimer une question, rendez vous dans l'encadré correspondant, choisissez la catégorie dans laquelle appartient la question que vous voulez supprimer puis validez.</p>
                    <p>Toutes les questions de cette catégorie apparaitront alors dans l'ordre alphabétique dans l'encadré.</p>
                    <p>Vous n'avez plus qu'à cocher les questions que vous voulez supprimer et de valider en cliquant sur "supprimer les questions selectionnées !!!ATTENTION!!! Cette opération est irréversible.</p>
                    <p>Pour supprimer un thème, rendez vous dans l'encadré en bas de page, puis sélectionnez le thème que vous voulez supprimer et enfin cliquez sur "supprimer". !!!ATTENTION!!! Tout comme pour les questions, cette opération est irréversible.</p>
                    <p>En supprimant un thème, vous supprimez également toutes les questions qui y sont rattachées.</p>
                </li>
                <li>
                    <h4>modifier une question</h4>
                    <p>Pour "modifier une question", il vous faut tout d'abord selectionner la catégorie de la question. Choisissez ensuite la question à modifier en cliquant dessus. La suite est quasiment identique à l'ajout de question.</p>
                    <p>Vous avez accès à toute les données de la question et il vous suffit simplement de modifier les champs que vous voulez rectifier (Pour ne pas modifier un champ, il vous suffit de laisser la valeur par défaut).</p>
                </li>
            </ul>
        </li>
    </ol>
</section>